---
- hosts: localhost
  gather_facts: false
  connection: local

- import_playbook: oc-project.yml
  tags:
    - always

- import_playbook: oc-operatorgroup.yml
  tags:
    - always

- import_playbook: oc-operatorhub.yml
  tags:
    - always

- import_playbook: oc-amq.yml
  tags:
    - always

- import_playbook: oc-smartgateway.yml
  tags:
    - sgateway
    - stf
    - never

- import_playbook: oc-stfobject.yml
  tags:
    - stf
    - never

- import_playbook: oc-grafana.yml
  tags:
    - grafana
    - never
