---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - name: execute requested tasks
      set_fact:
        execute: true
      tags:
        - sgateway
        - stf
        - grafana
      set_fact:
        execute: false

- import_playbook: oc-project.yml
  tags:
    - always

- import_playbook: oc-operatorgroup.yml
  tags:
    - always

- import_playbook: oc-operatorhub.yml
  tags:
    - always

- import_playbook: oc-amq.yml
  tags:
    - always

- import_playbook: oc-smartgateway.yml
  tags:
    - sgateway
    - stf
  when: execute == true

- import_playbook: oc-stfobject.yml
  tags:
    - stf
  when: execute == true

- import_playbook: oc-grafana.yml
  tags:
    - grafana
  when: execute == true
