- name: stf namepsace
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Subscribe to Active MQ Certificate Manager Operator.
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: amq7-cert-manager-operator
            namespace: openshift-operators
          spec:
            channel: 1.x
            installPlanApproval: Automatic
            name: amq7-cert-manager-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
