- name: Prepping STF For Installation
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Subscribe to the Service Telemetry Operator to Manage the monitoring applications
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: service-telemetry-operator
            namespace: service-telemetry
          spec:
            channel: stable-1.3
            installPlanApproval: Automatic
            name: service-telemetry-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
